version: '3.8'

services:
  # Сервис для FastAPI приложения
  app:
    build: .
    ports:
      - "8000:8000"  # Пробрасываем порт 8000 контейнера на 8000 локальной машины
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:8810533@db/cadastral_2  # Строка подключения к БД
    depends_on:
      - db  # Указываем, что сервис зависит от базы данных

  # Сервис для PostgreSQL
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8810533
      POSTGRES_DB: cadastral_2
    ports:
      - "5432:5432"  # Пробрасываем порт PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Для сохранения данных базы

# Создаем том для сохранения данных PostgreSQL
volumes:
  postgres_data: